(function(){
'use strict';
var C=window.HSCCommon,T=window.HSCI18N,DATA=window.HSC_DATA||{vehicles:[],parts:[]},vehicles=DATA.vehicles||[];
DATA.parts=DATA.parts||[];
var state={vehicle:null,paint:null,plate:null,parts:[],services:[],pack:'all',cat:'all'};
var services=[
 {id:'diagnostyka',name:'Diagnostyka pełna',desc:'Sprawdzenie auta i części po przyjęciu.'},
 {id:'kola',name:'Serwis kół / felg',desc:'Montaż i ustawienie zgodnie z modem.'},
 {id:'zawieszenie',name:'Serwis zawieszenia',desc:'Obsługa dostępnych elementów zawieszenia.'},
 {id:'hamulce',name:'Serwis hamulców',desc:'Kontrola i kompatybilne części.'},
 {id:'lakiernia',name:'Lakiernia',desc:'Zmiana wariantu lakieru, jeśli auto ją obsługuje.'},
 {id:'detailing',name:'Detailing / przygotowanie',desc:'Końcowe przygotowanie auta.'}
];
var icons={'Bodykit':'◩','Interior':'◫','Wheels / Rims':'◉','Engine upgrades':'⚙','Exterior':'⌁','Suspension':'↕','Brakes':'◍','Tires':'◎','Performance':'◆','Instruments':'◌','Nitrous':'N₂O'};
var colors={white:'#eee',black:'#151515',blue:'#3d73ff',red:'#e84c5a',green:'#44b875',yellow:'#ffd65d',gray:'#8f9098',grey:'#8f9098',silver:'#c7c9d2',orange:'#ff934c',purple:'#a65cff','pearl white':'#f9f5ff',aurora:'#cc75ff',custom:'#c680ff','custom 1':'#cc79ff','custom 2':'#78d5ff',base:'#aaa',eggs:'#f5dda3',police:'#4672ff'};
function q(s,r){return (r||document).querySelector(s)}function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function toast(m){var t=q('#toast');t.textContent=m;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},2200)}
function modal(html){q('#modal-content').innerHTML=html;q('#modal').classList.remove('hidden')}
function closeModal(){q('#modal').classList.add('hidden')}qa('[data-close-modal]').forEach(function(x){x.onclick=closeModal});
function renderFilters(){var packs=['all','GT Craft','New Cars','BRCC'];q('#pack-filters').innerHTML=packs.map(function(p){return '<button class="filter-chip '+(state.pack===p?'active':'')+'" data-pack="'+p+'">'+(p==='all'?'Wszystkie':p)+'</button>'}).join('');qa('[data-pack]').forEach(function(b){b.onclick=function(){state.pack=b.getAttribute('data-pack');renderFilters();renderVehicles()}})}
function renderVehicles(){var term=q('#vehicle-search').value.trim().toLowerCase();var list=vehicles.filter(function(v){return (state.pack==='all'||v.pack===state.pack)&&(!term||(v.name+' '+v.id+' '+v.category).toLowerCase().indexOf(term)>=0)});q('#vehicle-list').innerHTML=list.map(function(v){return '<button class="vehicle-item '+(state.vehicle&&state.vehicle.id===v.id?'active':'')+'" data-v="'+v.id+'"><b>'+C.esc(v.name)+'</b><small>'+v.id+' • '+C.esc(v.pack)+'</small></button>'}).join('')||'<div class="mini-empty">Brak wyników.</div>';qa('[data-v]').forEach(function(b){b.onclick=function(){selectVehicle(b.getAttribute('data-v'))}})}
function selectVehicle(id){state.vehicle=vehicles.find(function(v){return v.id===id});state.paint=null;state.plate=null;state.parts=[];state.services=[];state.cat='all';renderVehicles();renderConfig();renderSummary()}
function renderConfig(){var v=state.vehicle;if(!v){q('#vehicle-empty').classList.remove('hidden');q('#vehicle-config').classList.add('hidden');return}q('#vehicle-empty').classList.add('hidden');q('#vehicle-config').classList.remove('hidden');q('#selected-pack').textContent=v.pack;q('#selected-name').textContent=v.name;q('#selected-id').textContent=v.id+' • '+T.vcategory(v.category);
var cs=v.colors||[];q('#paint-options').innerHTML=cs.length?cs.map(function(c){var col=colors[String(c).toLowerCase()]||'#b66cff';return '<button data-color="'+C.esc(c)+'" class="'+(state.paint===c?'active':'')+'"><span class="color-dot" style="background:'+col+'"></span>'+C.esc(T.color(c))+'</button>'}).join(''):'<span class="muted">Brak osobnych wariantów lakieru.</span>';qa('[data-color]').forEach(function(b){b.onclick=function(){state.paint=b.getAttribute('data-color');renderConfig();renderSummary()}});
var plates=C.platesForVehicle(v);q('#plate-card').classList.toggle('hidden',!plates.length);q('#plate-options').innerHTML=plates.map(function(p){return '<button data-plate="'+C.esc(p)+'" class="'+(state.plate===p?'active':'')+'">'+C.esc(T.plate(p))+'</button>'}).join('');qa('[data-plate]').forEach(function(b){b.onclick=function(){state.plate=b.getAttribute('data-plate');renderConfig();renderSummary()}});
renderTabs();renderParts();renderServices()}
function vehicleParts(){if(!state.vehicle)return[];return DATA.parts.filter(function(p){return (p.cars||[]).indexOf(state.vehicle.id)>=0})}
function renderTabs(){var cats=['all'].concat(Array.from(new Set(vehicleParts().map(function(p){return p.category}))).sort());q('#mod-tabs').innerHTML=cats.map(function(c){return '<button data-cat="'+C.esc(c)+'" class="'+(state.cat===c?'active':'')+'">'+(c==='all'?'Wszystko':C.esc(T.category(c)))+'</button>'}).join('');qa('[data-cat]').forEach(function(b){b.onclick=function(){state.cat=b.getAttribute('data-cat');renderTabs();renderParts()}})}
function renderParts(){if(!state.vehicle)return;var all=vehicleParts(),term=q('#mod-search').value.trim().toLowerCase(),list=all.filter(function(p){return(state.cat==='all'||p.category===state.cat)&&(!term||(p.name+' '+T.part(p.name)+' '+p.category+' '+T.category(p.category)).toLowerCase().indexOf(term)>=0)});q('#mod-count').textContent=list.length+' pozycji';if(!all.length){q('#mod-grid').innerHTML='<div class="note" style="grid-column:1/-1">Ten model nie ma rozbudowanej listy wymiennych części w naszej bazie. Nie pokazujemy wymyślonych opcji.</div>';return}q('#mod-grid').innerHTML=list.map(function(p){var key=p.category+'|'+p.name,on=state.parts.indexOf(key)>=0;return '<article class="mod-card '+(on?'selected':'')+'" data-part="'+encodeURIComponent(key)+'"><span class="check">'+(on?'✓':'')+'</span><div class="mod-visual">'+(icons[p.category]||'◇')+'</div><b>'+C.esc(T.part(p.name))+'</b><small>'+C.esc(T.category(p.category))+'</small></article>'}).join('');qa('[data-part]').forEach(function(el){el.onclick=function(){var key=decodeURIComponent(el.getAttribute('data-part')),i=state.parts.indexOf(key);if(i>=0)state.parts.splice(i,1);else state.parts.push(key);renderParts();renderSummary()}})}
function renderServices(){q('#service-grid').innerHTML=services.map(function(s){var on=state.services.indexOf(s.id)>=0;return '<div class="service-item '+(on?'selected':'')+'" data-s="'+s.id+'"><b>'+(on?'✓ ':'')+C.esc(s.name)+'</b><small>'+C.esc(s.desc)+'</small></div>'}).join('');qa('[data-s]').forEach(function(el){el.onclick=function(){var id=el.getAttribute('data-s'),i=state.services.indexOf(id);if(i>=0)state.services.splice(i,1);else state.services.push(id);renderServices();renderSummary()}})}
function renderSummary(){var rows=[];if(state.vehicle)rows.push({n:state.vehicle.name,m:state.vehicle.id});if(state.paint)rows.push({n:'Lakier: '+T.color(state.paint),m:'nadwozie'});if(state.plate)rows.push({n:T.plate(state.plate),m:'tablica'});state.parts.forEach(function(k){var a=k.split('|');rows.push({n:T.part(a.slice(1).join('|')),m:T.category(a[0])})});state.services.forEach(function(id){var s=services.find(function(x){return x.id===id});if(s)rows.push({n:s.name,m:'usługa'})});q('#build-count').textContent=Math.max(0,rows.length-(state.vehicle?1:0));q('#build-summary').innerHTML=rows.length?rows.map(function(r){return '<div class="summary-item"><div><b>'+C.esc(r.n)+'</b><small>'+C.esc(r.m)+'</small></div></div>'}).join(''):'<div class="mini-empty">Jeszcze nic nie wybrano.</div>'}
function renderRegions(){q('#cn-region').innerHTML=C.cnRegions.map(function(r){return '<option value="'+r[0]+'">'+r[1]+' — '+r[2]+' ('+r[0]+')</option>'}).join('');updateCnPreview()}
function updateCnPreview(){var r=C.makeChinaReg(q('#cn-region').value,q('#cn-letter').value,q('#cn-suffix').value);q('#cn-preview').textContent=r.display+'   •   '+r.canonical}
function getReg(){if(q('#reg-kind').value==='CN')return C.makeChinaReg(q('#cn-region').value,q('#cn-letter').value,q('#cn-suffix').value);return C.makeLatinReg(q('#client-reg').value)}
function saveProject(){if(!state.vehicle)return toast('Najpierw wybierz auto.');var client=q('#client-name').value.trim();if(!client)return toast('Wpisz nick klienta.');var reg=getReg();if(!reg.canonical||reg.canonical.length<3)return toast('Uzupełnij rejestrację.');if(reg.kind==='CN'&&reg.suffix.length<3)return toast('Uzupełnij chińską rejestrację.');
var project={id:C.projectId(),createdAt:new Date().toISOString(),status:'PROJEKT KLIENTA',client:client,registration:reg,vehicle:{id:state.vehicle.id,name:state.vehicle.name,pack:state.vehicle.pack,itemId:state.vehicle.itemId},paint:state.paint,plateStyle:state.plate,parts:state.parts.map(function(k){var a=k.split('|');return{category:a.shift(),name:a.join('|')}}),services:state.services.map(function(id){var s=services.find(function(x){return x.id===id});return s?s.name:id}),note:q('#client-note').value.trim()};C.saveProject(project);var code=C.projectCode(project);modal('<div class="eyebrow">PROJEKT ZAPISANY</div><h2 style="margin:0 0 8px">'+C.esc(project.id)+'</h2><p class="muted">To nadal nie jest zlecenie. Przekaż ten kod pracownikowi przy przyjęciu auta.</p><div class="detail-grid"><div class="detail-box"><span>Auto</span><b>'+C.esc(project.vehicle.name)+'</b></div><div class="detail-box"><span>Rejestracja</span><b>'+C.esc(C.formatReg(project.registration))+'</b></div></div><label class="field-label" style="margin-top:16px">KOD PROJEKTU</label><textarea id="project-code" class="input project-code" readonly>'+C.esc(code)+'</textarea><button id="copy-project" class="btn primary wide" style="margin-top:10px">Kopiuj kod</button>');setTimeout(function(){q('#copy-project').onclick=function(){copy(code)}},0)}
function copy(t){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(t).then(function(){toast('Skopiowano kod.')}).catch(function(){fallback(t)});else fallback(t)}
function fallback(t){var a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();try{document.execCommand('copy');toast('Skopiowano kod.')}catch(e){toast('Zaznacz kod ręcznie.')}a.remove()}
function clearAll(){state={vehicle:null,paint:null,plate:null,parts:[],services:[],pack:'all',cat:'all'};q('#vehicle-search').value='';q('#mod-search').value='';renderFilters();renderVehicles();renderConfig();renderSummary()}
q('#vehicle-search').addEventListener('input',renderVehicles);q('#mod-search').addEventListener('input',renderParts);q('#save-project').onclick=saveProject;q('#clear-build').onclick=clearAll;
q('#reg-kind').onchange=function(){var cn=this.value==='CN';q('#reg-cn').classList.toggle('hidden',!cn);q('#reg-latin').classList.toggle('hidden',cn)};['#cn-region','#cn-letter','#cn-suffix'].forEach(function(s){q(s).addEventListener('input',updateCnPreview);q(s).addEventListener('change',updateCnPreview)});
renderRegions();renderFilters();renderVehicles();renderConfig();renderSummary();
})();