(function(){
'use strict';
var DATA=window.HSC_DATA||{vehicles:[],parts:[]};
var vehicles=DATA.vehicles||[];
DATA.parts=DATA.parts||[];
var state={view:'home',vehicle:null,paint:null,parts:[],services:[],modCat:'all',pack:'all'};
var STORAGE='hsc_customs_orders_v1';
var statuses=['NOWE','PRZYJĘCIE','WYCENA','ZAAKCEPTOWANE','OCZEKUJE NA CZĘŚCI','W NAPRAWIE','LAKIERNIA','TEST','GOTOWE DO ODBIORU','WYDANE'];
var services=[
 {id:'diagnostyka',name:'Diagnostyka pełna',desc:'Oględziny auta i sprawdzenie slotów / części.'},
 {id:'kola',name:'Serwis kół i opon',desc:'Montaż, zmiana setupu i kontrola.'},
 {id:'zawieszenie',name:'Serwis zawieszenia',desc:'Kontrola / ustawienie zgodnie z możliwościami moda.'},
 {id:'hamulce',name:'Serwis hamulców',desc:'Kontrola i wymiana kompatybilnych elementów.'},
 {id:'detailing',name:'Detailing / przygotowanie',desc:'Końcowe przygotowanie auta do odbioru.'},
 {id:'lakiernia',name:'Lakiernia',desc:'Zmiana wariantu lakieru Paint Gunem, jeżeli pack go obsługuje.'}
];
var catIcon={'Bodykit':'◩','Interior':'◫','Wheels / Rims':'◉','Engine upgrades':'⚙','Exterior':'⌁','Suspension':'↕','Brakes':'◍','Tires':'◎','Performance':'◆','Instruments':'◌','Nitrous':'N₂O'};
var colorMap={white:'#eee',black:'#151515',blue:'#3d73ff',red:'#e84c5a',green:'#44b875',yellow:'#ffd65d',gray:'#8f9098',grey:'#8f9098',silver:'#c7c9d2',orange:'#ff934c',purple:'#a65cff','pearl white':'#f9f5ff',aurora:'#cc75ff',custom:'#c680ff','custom 1':'#cc79ff','custom 2':'#78d5ff',base:'#aaa',eggs:'#f5dda3',police:'#4672ff'};
function qs(s,r){return (r||document).querySelector(s)} function qsa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function toast(msg){var t=qs('#toast');t.textContent=msg;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},2200)}
function go(view){state.view=view;qsa('.view').forEach(function(v){v.classList.remove('active')});var el=qs('#view-'+view);if(el)el.classList.add('active');window.scrollTo(0,0);if(view==='staff')renderStaff();if(view==='status')qs('#status-id').focus();location.hash=view==='home'?'':view}
qsa('[data-go]').forEach(function(b){b.addEventListener('click',function(){go(b.getAttribute('data-go'))})});
window.addEventListener('hashchange',function(){var h=location.hash.replace('#','');go(['client','staff','status'].indexOf(h)>=0?h:'home')});

function renderPackFilters(){var packs=['all','GT Craft','New Cars','BRCC'];qs('#pack-filters').innerHTML=packs.map(function(p){return '<button class="filter-chip '+(state.pack===p?'active':'')+'" data-pack="'+p+'">'+(p==='all'?'Wszystkie':p)+'</button>'}).join('');qsa('[data-pack]').forEach(function(b){b.onclick=function(){state.pack=b.getAttribute('data-pack');renderPackFilters();renderVehicleList()}})}
function renderVehicleList(){var term=qs('#vehicle-search').value.trim().toLowerCase();var list=vehicles.filter(function(v){return (state.pack==='all'||v.pack===state.pack)&&(!term||(v.name+' '+v.id+' '+v.category).toLowerCase().indexOf(term)>=0)});qs('#vehicle-list').innerHTML=list.map(function(v){return '<button class="vehicle-item '+(state.vehicle&&state.vehicle.id===v.id?'active':'')+'" data-vehicle="'+v.id+'"><b>'+esc(v.name)+'</b><small>'+v.id+' • '+esc(v.pack)+'</small></button>'}).join('')||'<div class="mini-empty">Brak wyników.</div>';qsa('[data-vehicle]').forEach(function(b){b.onclick=function(){selectVehicle(b.getAttribute('data-vehicle'))}})}
function selectVehicle(id){state.vehicle=vehicles.find(function(v){return v.id===id});state.paint=null;state.parts=[];state.services=[];state.modCat='all';renderVehicleList();renderConfig();renderBuild()}
function renderConfig(){var v=state.vehicle;if(!v){qs('#vehicle-empty').classList.remove('hidden');qs('#vehicle-config').classList.add('hidden');return}qs('#vehicle-empty').classList.add('hidden');qs('#vehicle-config').classList.remove('hidden');qs('#selected-pack').textContent=v.pack;qs('#selected-name').textContent=v.name;qs('#selected-id').textContent=v.id+' • '+v.category;
 var colors=v.colors||[];qs('#paint-options').innerHTML=colors.length?colors.map(function(c){var col=colorMap[String(c).toLowerCase()]||'#b66cff';return '<button data-color="'+esc(c)+'" class="'+(state.paint===c?'active':'')+'"><span class="color-dot" style="background:'+col+'"></span>'+esc(c)+'</button>'}).join(''):'<span class="muted">Brak osobnych wariantów lakieru wykrytych dla tego modelu.</span>';qsa('[data-color]').forEach(function(b){b.onclick=function(){state.paint=b.getAttribute('data-color');renderConfig();renderBuild()}});
 renderModTabs();renderModGrid();renderServices()}
function renderModTabs(){var parts=DATA.parts.filter(function(p){return (p.cars||[]).indexOf(state.vehicle.id)>=0});var cats=['all'].concat(Array.from(new Set(parts.map(function(p){return p.category}))).sort());qs('#mod-tabs').innerHTML=cats.map(function(c){return '<button data-cat="'+esc(c)+'" class="'+(state.modCat===c?'active':'')+'">'+(c==='all'?'Wszystko':esc(c))+'</button>'}).join('');qsa('[data-cat]').forEach(function(b){b.onclick=function(){state.modCat=b.getAttribute('data-cat');renderModTabs();renderModGrid()}})}
function renderModGrid(){if(!state.vehicle)return;var parts=DATA.parts.filter(function(p){return (p.cars||[]).indexOf(state.vehicle.id)>=0});var term=qs('#mod-search').value.trim().toLowerCase();var filtered=parts.filter(function(p){return (state.modCat==='all'||p.category===state.modCat)&&(!term||p.name.toLowerCase().indexOf(term)>=0)});qs('#mod-count').textContent=filtered.length+' pozycji';if(!parts.length){qs('#mod-grid').innerHTML='<div class="note" style="grid-column:1/-1">Ten model nie ma rozbudowanych wymiennych slotów takich jak GT Craft. Pokazujemy tylko faktyczne warianty lakieru oraz usługi warsztatowe — bez wymyślania części, których pack nie udostępnia.</div>';return}qs('#mod-grid').innerHTML=filtered.map(function(p,i){var key=p.category+'|'+p.name;var selected=state.parts.indexOf(key)>=0;return '<article class="mod-card '+(selected?'selected':'')+'" data-part="'+encodeURIComponent(key)+'"><span class="check">'+(selected?'✓':'')+'</span><div class="mod-visual">'+(catIcon[p.category]||'◇')+'</div><b>'+esc(p.name)+'</b><small>'+esc(p.category)+' • '+esc(state.vehicle.pack)+'</small></article>'}).join('')||'<div class="mini-empty">Brak pozycji w tej kategorii.</div>';qsa('[data-part]').forEach(function(el){el.onclick=function(){var key=decodeURIComponent(el.getAttribute('data-part'));var ix=state.parts.indexOf(key);if(ix>=0)state.parts.splice(ix,1);else state.parts.push(key);renderModGrid();renderBuild()}})}
function renderServices(){qs('#service-grid').innerHTML=services.map(function(s){var on=state.services.indexOf(s.id)>=0;return '<div class="service-item '+(on?'selected':'')+'" data-service="'+s.id+'"><b>'+(on?'✓ ':'')+esc(s.name)+'</b><small>'+esc(s.desc)+'</small></div>'}).join('');qsa('[data-service]').forEach(function(el){el.onclick=function(){var id=el.getAttribute('data-service'),ix=state.services.indexOf(id);if(ix>=0)state.services.splice(ix,1);else state.services.push(id);renderServices();renderBuild()}})}
function renderBuild(){var items=[];if(state.vehicle)items.push({name:state.vehicle.name,meta:state.vehicle.id,locked:true});if(state.paint)items.push({name:'Lakier: '+state.paint,meta:'wariant nadwozia',type:'paint'});state.parts.forEach(function(k){var a=k.split('|');items.push({name:a.slice(1).join('|'),meta:a[0],key:k,type:'part'})});state.services.forEach(function(id){var s=services.find(function(x){return x.id===id});if(s)items.push({name:s.name,meta:'usługa',key:id,type:'service'})});qs('#build-count').textContent=Math.max(0,items.length-(state.vehicle?1:0));qs('#build-summary').innerHTML=items.length?items.map(function(x){return '<div class="summary-item"><div><b>'+esc(x.name)+'</b><small>'+esc(x.meta)+'</small></div>'+(x.locked?'':'<button data-remove="'+encodeURIComponent((x.type||'')+'|'+(x.key||''))+'">×</button>')+'</div>'}).join(''):'<div class="mini-empty">Jeszcze nic nie wybrano.</div>';qsa('[data-remove]').forEach(function(b){b.onclick=function(){var val=decodeURIComponent(b.getAttribute('data-remove')),a=val.split('|'),type=a.shift(),key=a.join('|');if(type==='paint')state.paint=null;else if(type==='part'){var ix=state.parts.indexOf(key);if(ix>=0)state.parts.splice(ix,1)}else if(type==='service'){var j=state.services.indexOf(key);if(j>=0)state.services.splice(j,1)}renderConfig();renderBuild()}})}
function resetBuild(){state.vehicle=null;state.paint=null;state.parts=[];state.services=[];state.modCat='all';renderVehicleList();renderConfig();renderBuild()}
qs('#vehicle-search').addEventListener('input',renderVehicleList);qs('#mod-search').addEventListener('input',renderModGrid);qs('#clear-build').onclick=resetBuild;

function getOrders(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch(e){return []}}function saveOrders(x){localStorage.setItem(STORAGE,JSON.stringify(x))}
function makeId(){var d=new Date(),pad=function(n){return String(n).padStart(2,'0')};return 'HSC-'+String(d.getFullYear()).slice(-2)+pad(d.getMonth()+1)+pad(d.getDate())+'-'+Math.random().toString(16).slice(2,6).toUpperCase()}
function makeCode(order){var s=unescape(encodeURIComponent(JSON.stringify(order)));return 'HSC1:'+btoa(s)}function parseCode(code){if(code.indexOf('HSC1:')!==0)throw new Error('Zły format');return JSON.parse(decodeURIComponent(escape(atob(code.slice(5)))))}
qs('#submit-build').onclick=function(){if(!state.vehicle)return toast('Najpierw wybierz auto.');var name=qs('#client-name').value.trim(),reg=qs('#client-reg').value.trim();if(!name||!reg)return toast('Wpisz nick klienta i rejestrację.');var order={id:makeId(),createdAt:new Date().toISOString(),client:name,registration:reg.toUpperCase(),vehicle:{id:state.vehicle.id,name:state.vehicle.name,pack:state.vehicle.pack,itemId:state.vehicle.itemId},paint:state.paint,parts:state.parts.map(function(k){var a=k.split('|');return {category:a.shift(),name:a.join('|')}}),services:state.services.map(function(id){return services.find(function(x){return x.id===id}).name}),note:qs('#client-note').value.trim(),status:'NOWE',bay:null,paymentMethod:'NIE USTALONO',paymentStatus:'NIEOPŁACONE',history:[{at:new Date().toISOString(),text:'Klient wysłał konfigurację'}]};var orders=getOrders();orders.unshift(order);saveOrders(orders);showOrderCreated(order)};
function showOrderCreated(o){var code=makeCode(o);openModal('<div class="eyebrow">ZLECENIE UTWORZONE</div><h2>'+esc(o.id)+'</h2><p class="muted">Zapisz numer. Jeżeli pracownik korzysta z innego urządzenia, przekaż mu poniższy kod importu.</p><div class="detail-grid"><div class="detail-box"><span>Auto</span><b>'+esc(o.vehicle.name)+'</b></div><div class="detail-box"><span>Rejestracja</span><b>'+esc(o.registration)+'</b></div></div><label class="field-label" style="margin-top:18px">KOD IMPORTU</label><textarea id="created-code" class="input" rows="6" readonly>'+esc(code)+'</textarea><button class="btn primary wide" id="copy-created" style="margin-top:10px">Kopiuj kod</button>');setTimeout(function(){var b=qs('#copy-created');if(b)b.onclick=function(){copyText(qs('#created-code').value)}},0)}
function copyText(t){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(t).then(function(){toast('Skopiowano.')}).catch(function(){fallbackCopy(t)})}else fallbackCopy(t)}function fallbackCopy(t){var ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');toast('Skopiowano.')}catch(e){toast('Zaznacz kod ręcznie.')}ta.remove()}

function renderStaff(){var orders=getOrders();renderBays(orders);renderOrders(orders);updateStats(orders)}
function renderBays(orders){var active=orders.filter(function(o){return o.status!=='WYDANE'});var bays=[];bays.push({n:1,title:'PRZYJĘCIE AUTA',type:'intake',order:active.find(function(o){return o.bay===1})});for(var i=2;i<=8;i++)bays.push({n:i,title:'STANOWISKO UNIWERSALNE',order:active.find(function(o){return o.bay===i})});bays.push({n:'P',title:'LAKIERNIA',type:'paint',order:active.find(function(o){return o.bay==='PAINT'})});qs('#bay-grid').innerHTML=bays.map(function(b){var o=b.order;return '<div class="bay '+(b.type||'')+'"><div class="bay-num">'+(b.n==='P'?'STREFA SPECJALNA':'STANOWISKO '+b.n)+'</div><h4>'+b.title+'</h4><div class="bay-status">'+(o?esc(o.status):'WOLNE')+'</div>'+(o?'<div class="bay-car">'+esc(o.vehicle.name)+'<br><span class="muted">'+esc(o.registration)+' • '+esc(o.id)+'</span></div>':'')+'</div>'}).join('')}
function renderOrders(orders){var f=qs('#order-filter').value;var list=orders.filter(function(o){return f==='all'||o.status===f});qs('#order-list').innerHTML=list.length?list.map(function(o){return '<div class="order-row" data-order="'+o.id+'"><div><b>'+esc(o.id)+'</b><small>'+esc(o.client)+' • '+esc(o.registration)+'</small></div><div><b>'+esc(o.vehicle.name)+'</b><small>'+esc(o.vehicle.pack)+'</small></div><div><span class="status-pill">'+esc(o.status)+'</span></div><div><b>'+(o.bay?'ST. '+(o.bay==='PAINT'?'LAK':o.bay):'—')+'</b><small>stanowisko</small></div><div>›</div></div>'}).join(''):'<div class="mini-empty">Brak zleceń.</div>';qsa('[data-order]').forEach(function(el){el.onclick=function(){openOrder(el.getAttribute('data-order'))}})}
function updateStats(orders){qs('#stat-active').textContent=orders.filter(function(o){return ['WYDANE','GOTOWE DO ODBIORU'].indexOf(o.status)<0}).length;qs('#stat-waiting').textContent=orders.filter(function(o){return o.status==='OCZEKUJE NA CZĘŚCI'}).length;qs('#stat-ready').textContent=orders.filter(function(o){return o.status==='GOTOWE DO ODBIORU'}).length}
qs('#order-filter').onchange=renderStaff;
qs('#import-order').onclick=function(){try{var o=parseCode(qs('#import-code').value.trim());var orders=getOrders();if(orders.some(function(x){return x.id===o.id}))return toast('To zlecenie już istnieje.');orders.unshift(o);saveOrders(orders);qs('#import-code').value='';toast('Zaimportowano zlecenie.');renderStaff()}catch(e){toast('Nieprawidłowy kod zlecenia.')}};
qs('#seed-demo').onclick=function(){var v=vehicles.find(function(x){return x.id==='HSC-100'})||vehicles[0],o={id:makeId(),createdAt:new Date().toISOString(),client:'DemoPlayer',registration:'HSC 100',vehicle:{id:v.id,name:v.name,pack:v.pack,itemId:v.itemId},paint:(v.colors||[])[0]||null,parts:DATA.parts.filter(function(p){return (p.cars||[]).indexOf(v.id)>=0}).slice(0,3),services:['Diagnostyka pełna'],note:'Przykładowe zlecenie testowe.',status:'W NAPRAWIE',bay:2,paymentMethod:'KARTA',paymentStatus:'NIEOPŁACONE',history:[{at:new Date().toISOString(),text:'Przykładowe zlecenie'}]};var a=getOrders();a.unshift(o);saveOrders(a);renderStaff();toast('Dodano demo.')} ;
function openOrder(id){var orders=getOrders(),o=orders.find(function(x){return x.id===id});if(!o)return;var parts=(o.parts||[]).map(function(p){return '<span>'+esc(p.name||p)+'</span>'}).join('')||'<span>Brak części</span>';var serv=(o.services||[]).map(function(s){return '<span>'+esc(s)+'</span>'}).join('')||'<span>Brak dodatkowych usług</span>';var bayOpts=['','1','2','3','4','5','6','7','8','PAINT'].map(function(x){return '<option value="'+x+'" '+(String(o.bay||'')===x?'selected':'')+'>'+(x===''?'Brak stanowiska':x==='PAINT'?'Lakiernia':'Stanowisko '+x)+'</option>'}).join('');var stOpts=statuses.map(function(s){return '<option '+(o.status===s?'selected':'')+'>'+s+'</option>'}).join('');openModal('<div class="eyebrow">'+esc(o.id)+'</div><h2 style="margin-top:0">'+esc(o.vehicle.name)+'</h2><div class="detail-grid"><div class="detail-box"><span>Klient</span><b>'+esc(o.client)+'</b></div><div class="detail-box"><span>Rejestracja</span><b>'+esc(o.registration)+'</b></div><div class="detail-box"><span>Lakier</span><b>'+esc(o.paint||'bez zmian')+'</b></div><div class="detail-box"><span>Pack</span><b>'+esc(o.vehicle.pack)+'</b></div></div><h4>Modyfikacje</h4><div class="part-list">'+parts+'</div><h4>Usługi</h4><div class="part-list">'+serv+'</div>'+(o.note?'<div class="note">'+esc(o.note)+'</div>':'')+'<div class="modal-controls"><div><label class="field-label">STATUS</label><select id="edit-status" class="input">'+stOpts+'</select></div><div><label class="field-label">STANOWISKO</label><select id="edit-bay" class="input">'+bayOpts+'</select></div><div><label class="field-label">PŁATNOŚĆ</label><select id="edit-payment-method" class="input"><option '+(o.paymentMethod==='NIE USTALONO'?'selected':'')+'>NIE USTALONO</option><option '+(o.paymentMethod==='KARTA'?'selected':'')+'>KARTA</option><option '+(o.paymentMethod==='GOTÓWKA'?'selected':'')+'>GOTÓWKA</option></select></div><div><label class="field-label">STATUS PŁATNOŚCI</label><select id="edit-payment-status" class="input"><option '+(o.paymentStatus==='NIEOPŁACONE'?'selected':'')+'>NIEOPŁACONE</option><option '+(o.paymentStatus==='ZALICZKA'?'selected':'')+'>ZALICZKA</option><option '+(o.paymentStatus==='OPŁACONE'?'selected':'')+'>OPŁACONE</option></select></div></div><button id="save-order" class="btn primary wide" style="margin-top:14px">Zapisz zmiany</button>');setTimeout(function(){qs('#save-order').onclick=function(){var old=o.status;o.status=qs('#edit-status').value;var b=qs('#edit-bay').value;o.bay=b===''?null:(b==='PAINT'?'PAINT':Number(b));o.paymentMethod=qs('#edit-payment-method').value;o.paymentStatus=qs('#edit-payment-status').value;if(old!==o.status){o.history=o.history||[];o.history.push({at:new Date().toISOString(),text:'Status: '+o.status})}saveOrders(orders);closeModal();renderStaff();toast('Zapisano zlecenie.')}} ,0)}

function openModal(html){qs('#modal-content').innerHTML=html;qs('#modal').classList.remove('hidden')}function closeModal(){qs('#modal').classList.add('hidden')}qsa('[data-close-modal]').forEach(function(x){x.onclick=closeModal});
qs('#status-check').onclick=function(){var id=qs('#status-id').value.trim().toUpperCase(),o=getOrders().find(function(x){return x.id.toUpperCase()===id});var el=qs('#status-result');if(!o){el.innerHTML='<div class="note">Nie znaleziono zlecenia w tej przeglądarce.</div>';return}var tl=statuses.map(function(s){return '<span class="'+(s===o.status?'current':'')+'">'+s+'</span>'}).join('');el.innerHTML='<div class="status-card"><div class="pack-tag">'+esc(o.vehicle.pack)+'</div><h3>'+esc(o.vehicle.name)+'</h3><div class="detail-grid"><div class="detail-box"><span>Status</span><b>'+esc(o.status)+'</b></div><div class="detail-box"><span>Stanowisko</span><b>'+(o.bay?esc(o.bay==='PAINT'?'Lakiernia':o.bay):'—')+'</b></div><div class="detail-box"><span>Płatność</span><b>'+esc(o.paymentMethod)+'</b></div><div class="detail-box"><span>Status płatności</span><b>'+esc(o.paymentStatus)+'</b></div></div><div class="timeline">'+tl+'</div></div>'};

renderPackFilters();renderVehicleList();renderConfig();renderBuild();var initial=location.hash.replace('#','');go(['client','staff','status'].indexOf(initial)>=0?initial:'home');
})();