(function(){
'use strict';
var C=window.HSCCommon,T=window.HSCI18N;
var DATA=window.HSC_DATA||{vehicles:[],parts:[]};
DATA.parts=DATA.parts||[];
var SESSION='hsc_staff_session_v1';
var PARTS_KEY='hsc_parts_orders_v1';
var partCats=[{id:1,name:'Silnik / osiągi'},{id:2,name:'Zawieszenie'},{id:3,name:'Hamulce'},{id:4,name:'Koła / opony'},{id:5,name:'Nadwozie / pakiet karoserii'},{id:6,name:'Wnętrze'},{id:7,name:'Wskaźniki / elektryka'},{id:8,name:'Pozostałe części'}];
var statuses=['PRZYJĘCIE','WYCENA','ZAAKCEPTOWANE','OCZEKUJE NA CZĘŚCI','W NAPRAWIE','LAKIERNIA','TEST','GOTOWE DO ODBIORU','WYDANE'];
function q(s,r){return (r||document).querySelector(s)}function qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function toast(m){var t=q('#toast');t.textContent=m;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},2200)}
function modal(html){q('#modal-content').innerHTML=html;q('#modal').classList.remove('hidden')}
function closeModal(){q('#modal').classList.add('hidden')}qa('[data-close-modal]').forEach(function(x){x.onclick=closeModal});
function showApp(){q('#auth-screen').style.display='none';q('#staff-app').classList.remove('hidden');renderAll()}
function showAuth(){q('#auth-screen').style.display='grid';q('#staff-app').classList.add('hidden');var first=!C.ownerPinExists();q('#auth-title').textContent=first?'Pierwsze uruchomienie Staff OS':'Weryfikacja pracownika';q('#auth-copy').textContent=first?'Ustaw PIN właściciela dla tego urządzenia.':'Wpisz PIN pracownika, aby otworzyć panel warsztatu.';q('#auth-submit').textContent=first?'Ustaw PIN i otwórz panel':'Zaloguj';q('#auth-note').textContent=first?'To jest obecnie weryfikacja lokalna na tym urządzeniu. Przy podpinaniu wspólnej bazy zamienimy ją na prawdziwe konta pracowników i logowanie serwerowe.':'';q('#staff-pin').value='';q('#staff-pin').focus()}
async function auth(){var pin=q('#staff-pin').value.trim();if(pin.length<4)return toast('PIN musi mieć minimum 4 znaki.');try{if(!C.ownerPinExists()){await C.setupOwnerPin(pin);sessionStorage.setItem(SESSION,'1');toast('PIN zapisany.');showApp()}else if(await C.verifyOwnerPin(pin)){sessionStorage.setItem(SESSION,'1');showApp()}else toast('Nieprawidłowy PIN.')}catch(e){toast('Nie udało się zweryfikować PIN-u.')}}
q('#auth-submit').onclick=auth;q('#staff-pin').addEventListener('keydown',function(e){if(e.key==='Enter')auth()});q('#logout').onclick=function(){sessionStorage.removeItem(SESSION);showAuth()};

function setTab(name){qa('[data-tab]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-tab')===name)});qa('.panel-view').forEach(function(p){p.classList.add('hidden')});q('#tab-'+name).classList.remove('hidden');if(name==='projects')renderProjects();if(name==='orders')renderOrders();if(name==='bays')renderBays();if(name==='parts')renderPartsOrders()}
qa('[data-tab]').forEach(function(b){b.onclick=function(){setTab(b.getAttribute('data-tab'))}});

function renderAll(){renderProjects();renderOrders();renderBays();renderPartsOrders()}
function activeProjects(){return C.listProjects().filter(function(p){return !p.convertedOrderId})}
function renderProjects(){var list=activeProjects();q('#project-count').textContent=list.length+' oczekujących';q('#project-list').innerHTML=list.length?list.map(function(p){return '<div class="project-row" data-project="'+C.esc(p.id)+'"><div><b>'+C.esc(p.id)+'</b><small>'+new Date(p.createdAt).toLocaleString('pl-PL')+'</small></div><div><b>'+C.esc(p.vehicle.name)+'</b><small>'+C.esc(p.vehicle.pack)+'</small></div><div><b>'+C.esc(p.client)+'</b><small>'+C.esc(C.formatReg(p.registration))+'</small></div><div><span class="status-pill">PROJEKT</span></div><div>›</div></div>'}).join(''):'<div class="mini-empty">Brak projektów oczekujących.</div>';qa('[data-project]').forEach(function(el){el.onclick=function(){openProject(el.getAttribute('data-project'))}})}
q('#import-project').onclick=function(){try{var p=C.parseProjectCode(q('#project-code').value.trim());if(!p||!p.id||!p.vehicle)throw new Error('BAD');var all=C.listProjects();if(all.some(function(x){return x.id===p.id}))return toast('Ten projekt już jest zapisany.');C.saveProject(p);q('#project-code').value='';renderProjects();toast('Projekt klienta zaimportowany.')}catch(e){toast('Nieprawidłowy kod projektu.')}};

function vehicleDef(id){return (DATA.vehicles||[]).find(function(v){return v.id===id})}
function compatibleParts(id){return (DATA.parts||[]).filter(function(p){return (p.cars||[]).indexOf(id)>=0})}
function openProject(id){var p=C.listProjects().find(function(x){return x.id===id});if(!p)return;var vd=vehicleDef(p.vehicle.id)||{colors:[]};var current=(p.parts||[]).map(function(x){return x.category+'|'+x.name});var options=compatibleParts(p.vehicle.id).filter(function(x){return current.indexOf(x.category+'|'+x.name)<0}).slice(0,500);
var parts=(p.parts||[]).map(function(x,i){return '<span>'+C.esc(T.part(x.name))+' <button data-rm-part="'+i+'" style="border:0;background:transparent;color:#e89aff;cursor:pointer">×</button></span>'}).join('')||'<span>Brak wybranych części</span>';
var colorOpts=['<option value="">Bez zmian</option>'].concat((vd.colors||[]).map(function(c){return '<option '+(p.paint===c?'selected':'')+'>'+C.esc(T.color(c))+'</option>'})).join('');
var plateOpts=['<option value="">Brak / bez zmian</option>'].concat(C.platesForVehicle(vd).map(function(x){return '<option '+(p.plateStyle===x?'selected':'')+'>'+C.esc(T.plate(x))+'</option>'})).join('');
var addOpts='<option value="">Dodaj kompatybilną część...</option>'+options.map(function(x){return '<option value="'+C.esc(x.category+'|'+x.name)+'">'+C.esc(T.category(x.category)+' — '+T.part(x.name))+'</option>'}).join('');
modal('<div class="eyebrow">PROJEKT KLIENTA • '+C.esc(p.id)+'</div><h2 style="margin:0 0 8px">'+C.esc(p.vehicle.name)+'</h2><p class="muted">Tu możesz poprawić projekt po rozmowie z klientem. Oficjalne zlecenie jeszcze nie istnieje.</p><div class="detail-grid"><div class="detail-box"><span>Klient</span><b>'+C.esc(p.client)+'</b></div><div class="detail-box"><span>Rejestracja</span><b>'+C.esc(C.formatReg(p.registration))+'</b></div><div class="detail-box"><span>Pack</span><b>'+C.esc(p.vehicle.pack)+'</b></div><div class="detail-box"><span>Silnik</span><b>Fabryczny • bez swapu</b></div></div><div class="modal-controls"><div><label class="field-label">LAKIER</label><select id="project-paint" class="input">'+colorOpts+'</select></div><div><label class="field-label">TABLICA</label><select id="project-plate" class="input">'+plateOpts+'</select></div></div><h4>Modyfikacje</h4><div id="project-parts" class="part-list">'+parts+'</div><div style="display:flex;gap:8px;margin-top:10px"><select id="add-part" class="input">'+addOpts+'</select><button id="add-part-btn" class="btn ghost">Dodaj</button></div><label class="field-label" style="margin-top:16px">UWAGI / USTALENIA PO ROZMOWIE</label><textarea id="project-note" class="input" rows="4">'+C.esc(p.note||'')+'</textarea><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px"><button id="save-project-edit" class="btn ghost">Zapisz zmiany projektu</button><button id="create-order" class="btn primary">UTWÓRZ OFICJALNE ZLECENIE</button></div>');
setTimeout(function(){
  function redrawParts(){q('#project-parts').innerHTML=(p.parts||[]).map(function(x,i){return '<span>'+C.esc(T.part(x.name))+' <button data-rm-part="'+i+'" style="border:0;background:transparent;color:#e89aff;cursor:pointer">×</button></span>'}).join('')||'<span>Brak wybranych części</span>';qa('[data-rm-part]').forEach(function(b){b.onclick=function(){p.parts.splice(Number(b.getAttribute('data-rm-part')),1);redrawParts()}})}
  redrawParts();
  q('#add-part-btn').onclick=function(){var v=q('#add-part').value;if(!v)return;var a=v.split('|');p.parts=p.parts||[];p.parts.push({category:a.shift(),name:a.join('|')});q('#add-part').selectedIndex=0;redrawParts()};
  q('#save-project-edit').onclick=function(){syncProjectFields(p);C.saveProject(p);toast('Projekt poprawiony.');closeModal();renderProjects()};
  q('#create-order').onclick=function(){syncProjectFields(p);createOrderFromProject(p)}
},0)}
function syncProjectFields(p){p.paint=q('#project-paint').value||null;p.plateStyle=q('#project-plate').value||null;p.note=q('#project-note').value.trim();p.lastEditedAt=new Date().toISOString()}

function createOrderFromProject(p){var order={id:C.orderId(),projectId:p.id,createdAt:new Date().toISOString(),client:p.client,registration:p.registration,vehicle:p.vehicle,paint:p.paint||null,plateStyle:p.plateStyle||null,parts:(p.parts||[]).slice(),services:(p.services||[]).slice(),note:p.note||'',status:'PRZYJĘCIE',bay:1,paymentMethod:'NIE USTALONO',paymentStatus:'NIEOPŁACONE',history:[{at:new Date().toISOString(),text:'Oficjalne zlecenie utworzone po przyjęciu auta'}]};C.saveOrder(order);p.convertedOrderId=order.id;p.convertedAt=new Date().toISOString();C.saveProject(p);closeModal();renderAll();toast('Utworzono '+order.id+'.');setTab('orders');openOrder(order.id)}

function renderOrders(){var list=C.listOrders(),filter=q('#order-filter').value;if(filter!=='all')list=list.filter(function(o){return o.status===filter});q('#order-list').innerHTML=list.length?list.map(function(o){return '<div class="order-row" data-order="'+C.esc(o.id)+'"><div><b>'+C.esc(o.id)+'</b><small>'+C.esc(o.client)+' • '+C.esc(C.formatReg(o.registration))+'</small></div><div><b>'+C.esc(o.vehicle.name)+'</b><small>'+C.esc(o.vehicle.pack)+'</small></div><div><span class="status-pill">'+C.esc(o.status)+'</span></div><div><b>'+(o.bay==='PAINT'?'LAK':(o.bay||'—'))+'</b><small>stanowisko</small></div><div>›</div></div>'}).join(''):'<div class="mini-empty">Brak zleceń.</div>';qa('[data-order]').forEach(function(el){el.onclick=function(){openOrder(el.getAttribute('data-order'))}})}
q('#order-filter').onchange=renderOrders;
function openOrder(id){var orders=C.listOrders(),o=orders.find(function(x){return x.id===id});if(!o)return;var partHtml=(o.parts||[]).map(function(x){return '<span>'+C.esc(T.part(x.name||x))+'</span>'}).join('')||'<span>Brak części</span>';var stat=statuses.map(function(s){return '<option '+(o.status===s?'selected':'')+'>'+s+'</option>'}).join('');var bays=['','1','2','3','4','5','6','7','8','PAINT'].map(function(b){var label=b===''?'Brak':b==='PAINT'?'Lakiernia':'Stanowisko '+b;return '<option value="'+b+'" '+(String(o.bay||'')===b?'selected':'')+'>'+label+'</option>'}).join('');
modal('<div class="eyebrow">'+C.esc(o.id)+'</div><h2 style="margin:0 0 8px">'+C.esc(o.vehicle.name)+'</h2><div class="detail-grid"><div class="detail-box"><span>Klient</span><b>'+C.esc(o.client)+'</b></div><div class="detail-box"><span>Rejestracja</span><b>'+C.esc(C.formatReg(o.registration))+'</b></div><div class="detail-box"><span>Lakier</span><b>'+C.esc(o.paint?T.color(o.paint):'bez zmian')+'</b></div><div class="detail-box"><span>Tablica</span><b>'+C.esc(o.plateStyle?T.plate(o.plateStyle):'bez zmian')+'</b></div></div><h4>Modyfikacje</h4><div class="part-list">'+partHtml+'</div><div class="modal-controls"><div><label class="field-label">STATUS</label><select id="edit-status" class="input">'+stat+'</select></div><div><label class="field-label">STANOWISKO</label><select id="edit-bay" class="input">'+bays+'</select></div><div><label class="field-label">PŁATNOŚĆ</label><select id="edit-pay-method" class="input"><option '+(o.paymentMethod==='NIE USTALONO'?'selected':'')+'>NIE USTALONO</option><option '+(o.paymentMethod==='KARTA'?'selected':'')+'>KARTA</option><option '+(o.paymentMethod==='GOTÓWKA'?'selected':'')+'>GOTÓWKA</option></select></div><div><label class="field-label">STATUS PŁATNOŚCI</label><select id="edit-pay-status" class="input"><option '+(o.paymentStatus==='NIEOPŁACONE'?'selected':'')+'>NIEOPŁACONE</option><option '+(o.paymentStatus==='ZALICZKA'?'selected':'')+'>ZALICZKA</option><option '+(o.paymentStatus==='OPŁACONE'?'selected':'')+'>OPŁACONE</option></select></div></div><label class="field-label" style="margin-top:14px">NOTATKI WARSZTATU</label><textarea id="order-note" class="input" rows="4">'+C.esc(o.note||'')+'</textarea><button id="save-order" class="btn primary wide" style="margin-top:12px">Zapisz zlecenie</button>');
setTimeout(function(){q('#save-order').onclick=function(){var old=o.status;o.status=q('#edit-status').value;var b=q('#edit-bay').value;o.bay=b===''?null:(b==='PAINT'?'PAINT':Number(b));o.paymentMethod=q('#edit-pay-method').value;o.paymentStatus=q('#edit-pay-status').value;o.note=q('#order-note').value.trim();if(old!==o.status){o.history=o.history||[];o.history.push({at:new Date().toISOString(),text:'Status: '+o.status})}C.saveOrder(o);closeModal();renderAll();toast('Zlecenie zapisane.')}} ,0)}

function renderBays(){var active=C.listOrders().filter(function(o){return o.status!=='WYDANE'}),b=[];b.push({n:1,title:'PRZYJĘCIE AUTA',type:'intake'});for(var i=2;i<=8;i++)b.push({n:i,title:'STANOWISKO UNIWERSALNE'});b.push({n:'P',title:'LAKIERNIA',type:'paint'});b.forEach(function(x){x.order=active.find(function(o){return o.bay===(x.n==='P'?'PAINT':x.n)})});q('#bay-grid').innerHTML=b.map(function(x){var o=x.order;return '<div class="bay '+(x.type||'')+'"><div class="bay-num">'+(x.n==='P'?'STREFA SPECJALNA':'STANOWISKO '+x.n)+'</div><h4>'+x.title+'</h4><div class="bay-status">'+(o?C.esc(o.status):'WOLNE')+'</div>'+(o?'<div class="bay-car">'+C.esc(o.vehicle.name)+'<br><span class="muted">'+C.esc(C.formatReg(o.registration))+' • '+C.esc(o.id)+'</span></div>':'')+'</div>'}).join('')}

function getPartsOrders(){try{return JSON.parse(localStorage.getItem(PARTS_KEY)||'[]')}catch(e){return[]}}
function savePartsOrders(a){localStorage.setItem(PARTS_KEY,JSON.stringify(a))}
function renderPartsOrders(){
 var orderSel=q('#parts-order-id'),catSel=q('#parts-category');if(!orderSel||!catSel)return;
 var orders=C.listOrders().filter(function(o){return o.status!=='WYDANE'});
 orderSel.innerHTML='<option value="">Wybierz zlecenie...</option>'+orders.map(function(o){return '<option value="'+C.esc(o.id)+'">'+C.esc(o.id+' — '+o.vehicle.name+' — '+C.formatReg(o.registration))+'</option>'}).join('');
 catSel.innerHTML=partCats.map(function(x){return '<option value="'+x.id+'">'+x.id+'. '+C.esc(x.name)+'</option>'}).join('');
 var a=getPartsOrders();q('#parts-count').textContent=a.length+' zapisanych';
 q('#parts-list').innerHTML=a.length?a.map(function(x,i){return '<div class="order-row" style="grid-template-columns:1.15fr 1.5fr 1fr auto"><div><b>'+C.esc(x.orderId)+'</b><small>'+C.esc(x.categoryName)+'</small></div><div><b>'+C.esc(x.name)+'</b><small>Ilość: '+x.qty+'</small></div><div><span class="status-pill">'+C.esc(x.state)+'</span><small>/trigger hsc_part set '+x.category+'</small></div><div><button class="btn ghost" data-part-action="'+i+'" style="padding:8px 10px">Akcja</button></div></div>'}).join(''):'<div class="mini-empty">Brak zapisanych zamówień części.</div>';
 qa('[data-part-action]').forEach(function(b){b.onclick=function(){openPartsAction(Number(b.getAttribute('data-part-action')))}})
}
function openPartsAction(i){var a=getPartsOrders(),x=a[i];if(!x)return;var cmd='/trigger hsc_part set '+x.category;modal('<div class="eyebrow">DOSTAWA CZĘŚCI</div><h2 style="margin-top:0">'+C.esc(x.name)+'</h2><div class="detail-grid"><div class="detail-box"><span>Zlecenie</span><b>'+C.esc(x.orderId)+'</b></div><div class="detail-box"><span>Kategoria</span><b>'+C.esc(x.categoryName)+'</b></div></div><label class="field-label" style="margin-top:15px">KOMENDA DATAPACKA</label><input id="parts-command" class="input" readonly value="'+C.esc(cmd)+'"><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px"><button id="copy-parts-command" class="btn ghost">Kopiuj komendę</button><button id="mark-parts-sent" class="btn primary">Oznacz: W DRODZE</button></div><button id="remove-parts-order" class="btn danger wide" style="margin-top:8px">Usuń wpis</button>');setTimeout(function(){q('#copy-parts-command').onclick=function(){var t=q('#parts-command');t.select();document.execCommand('copy');toast('Skopiowano komendę.')};q('#mark-parts-sent').onclick=function(){x.state='W DRODZE';savePartsOrders(a);closeModal();renderPartsOrders();toast('Dostawa oznaczona jako uruchomiona.')};q('#remove-parts-order').onclick=function(){a.splice(i,1);savePartsOrders(a);closeModal();renderPartsOrders()}},0)}
if(q('#parts-create'))q('#parts-create').onclick=function(){var oid=q('#parts-order-id').value,name=q('#parts-name').value.trim(),cat=Number(q('#parts-category').value),qty=Math.max(1,Number(q('#parts-qty').value)||1);if(!oid)return toast('Wybierz zlecenie.');if(!name)return toast('Wpisz nazwę części.');var c=partCats.find(function(x){return x.id===cat});var a=getPartsOrders();a.unshift({id:'PART-'+Date.now(),orderId:oid,category:cat,categoryName:c.name,name:name,qty:qty,state:'DO URUCHOMIENIA',createdAt:new Date().toISOString()});savePartsOrders(a);q('#parts-name').value='';q('#parts-qty').value='1';renderPartsOrders();toast('Zamówienie części zapisane.')}

if(sessionStorage.getItem(SESSION)==='1'&&C.ownerPinExists())showApp();else showAuth();
})();